#!/usr/bin/env bash
# kde-macos-config — sync.sh
# Snapshots the live KDE config into config/ as a record of what is actually
# applied on this machine. These snapshots are DIAGNOSTIC: nothing in this repo
# reads them (apply.sh drives everything through kwriteconfig6 and the Plasma
# scripting API), so they exist to make a config diff reviewable, not to be
# portable input.
#
# Machine-specific noise is normalized away so that re-running sync on a
# different machine (or after a Plasma upgrade) does not churn the diff:
#   - per-desktop [Tiling][<uuid>] sections and freshly regenerated desktop IDs
#   - per-screen activityId UUIDs
#   - the [Updates] migration log
# NOTE: Plasma also generates the numeric [Containments][N] / [Applets][N]
# indices, which differ per machine and are NOT normalized - a snapshot diff
# across two machines will still show those renumbered.
#
# Usage:
#   ./sync.sh            # snapshot + show git status (does NOT stage or commit)
#   ./sync.sh --check    # read-only drift report; writes nothing, exits 1 on drift
#   ./sync.sh --commit   # snapshot + commit with a generated message
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"; cd "$ROOT"
CFG="$HOME/.config"
C="$ROOT/config"

usage(){
  cat <<'EOF'
usage: sync.sh [--check | --commit]
  (no args)  snapshot the live KDE config into config/, then show git status
  --check    read-only: report drift between the live config and config/,
             write nothing, exit 1 if anything drifted
  --commit   snapshot config/, then commit it with a generated message
EOF
}

MODE="sync"
case "${1:-}" in
  "")        ;;
  --commit)  MODE="commit" ;;
  --check)   MODE="check"  ;;
  -h|--help) usage; exit 0 ;;
  # An unknown flag used to be ignored, so "sync.sh --check" quietly rewrote every
  # snapshot - indistinguishable from a check that found nothing. Reject it.
  *) echo "sync.sh: unknown argument '$1' (expected --check or --commit)" >&2
     usage >&2; exit 2 ;;
esac
if [ "$#" -gt 1 ]; then
  echo "sync.sh: expected at most one argument, got $#" >&2
  exit 2
fi

mkdir -p "$C"

# live file -> repo snapshot (one destination per live file).
# Entries are "<live file>::<snapshot>". The :: separator matters: splitting on
# whitespace would silently fold column-alignment padding into the path.
PAIRS=(
"$CFG/plasma-org.kde.plasma.desktop-appletsrc::$C/applied-appletsrc.conf"
"$CFG/plasmashellrc::$C/applied-plasmashellrc.conf"
"$CFG/kdeglobals::$C/applied-kdeglobals.conf"
"$CFG/kwinrc::$C/applied-kwinrc.conf"
"$CFG/kcminputrc::$C/applied-kcminputrc.conf"
"$CFG/ksplashrc::$C/applied-ksplashrc.conf"
"$CFG/gtk-3.0/settings.ini::$C/applied-gtk3.ini"
"$CFG/gtk-4.0/settings.ini::$C/applied-gtk4.ini"
"$CFG/fontconfig/fonts.conf::$C/applied-fontconfig.ini"
)

# kwinrc: drop per-desktop [Tiling][<uuid>] sections (header AND body - the
# header carries the UUID, so keeping it would still churn) and normalize the
# remaining per-desktop UUIDs. Id_2..Id_4 are regenerated by every apply; Id_1 is
# stable on one machine but still differs between machines, so all of them
# collapse to a placeholder and the snapshot carries no machine identity.
norm_kwinrc() {
  awk '
    /^\[Tiling\]\[/ { tiling = 1; next }
    /^\[/ { tiling = 0; print; next }
    tiling { next }
    /^Id_[0-9]+=/ { n++; print "Id_" n "=<desktop-uuid>"; next }
    { print }
  '
}

# appletsrc: per-screen UUIDs -> stable placeholder.
norm_appletsrc() {
  sed -E 's/^(activityId=)[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-.*$/\1<screen-uuid>/'
}

# plasmashellrc: drop the [Updates] migration log (a long, machine-specific,
# Plasma-version-dependent path list).
norm_plasmashellrc() {
  awk '/^\[Updates\]$/ { skip = 1; next } /^\[/ { skip = 0 } !skip { print }'
}

# KConfig writes a blank line before every group, so stripping a trailing group
# (e.g. [Updates]) leaves a dangling blank line at EOF. Trim trailing blank
# lines from the normalized snapshots so the diffs stay clean and stable.
squeeze_trailing_blanks() {
  awk '{ b[NR] = $0 } END { last = NR
         while (last > 0 && b[last] ~ /^[[:space:]]*$/) last--
         for (i = 1; i <= last; i++) print b[i] }'
}

# Render the normalized snapshot for one pair to stdout. The sync and --check
# paths BOTH go through here, so they can never normalize differently: a checker
# with its own copy of the rules reports phantom drift, or silently misses real
# drift, and either way it is no longer a check of what sync actually writes.
render_snapshot(){
  local src="$1" dst="$2"
  case "$(basename "$dst")" in
    applied-kwinrc.conf)         norm_kwinrc        < "$src" | squeeze_trailing_blanks ;;
    applied-appletsrc.conf)      norm_appletsrc     < "$src" | squeeze_trailing_blanks ;;
    applied-plasmashellrc.conf)  norm_plasmashellrc < "$src" | squeeze_trailing_blanks ;;
    *)                           cat "$src" ;;
  esac
}

ver="$(git rev-parse --short HEAD)"

# ---- read-only drift check ------------------------------------------------
if [ "$MODE" = "check" ]; then
  echo "=== kde-macos-config: sync --check ($(date +%Y-%m-%d\ %H:%M:%S)) ==="
  echo "read-only: no files will be written, fc-cache will not run"
  tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
  drift=0
  for pair in "${PAIRS[@]}"; do
    src="${pair%%::*}"; dst="${pair##*::}"
    name="config/$(basename "$dst")"
    if [ ! -f "$src" ]; then
      if [ -f "$dst" ]; then
        echo "  stale    $name (snapshot exists but the live file is gone: ${src/#$HOME/~})"
      else
        echo "  n/a      $name (no live file: ${src/#$HOME/~})"
      fi
      continue
    fi
    render_snapshot "$src" "$dst" > "$tmp"
    if [ ! -f "$dst" ]; then
      echo "  MISSING  $name (live config has content, snapshot absent)"
      drift=1
    elif cmp -s "$tmp" "$dst"; then
      echo "  ok       $name"
    else
      echo "  DRIFT    $name"
      diff -u --label "$name (committed)" --label "$name (live, normalized)" \
        "$dst" "$tmp" | sed -n '3,14p' | sed 's/^/           /' || true
      drift=1
    fi
  done
  if [ "$drift" -eq 0 ]; then
    echo "=== check: in sync with the live config ==="
    exit 0
  fi
  echo "=== check: DRIFT - run ./sync.sh to refresh the snapshots ==="
  exit 1
fi

# ---- snapshot ------------------------------------------------------------
echo "=== kde-macos-config: sync ($(date +%Y-%m-%d\ %H:%M:%S)) ==="
changed=0
for pair in "${PAIRS[@]}"; do
  src="${pair%%::*}"; dst="${pair##*::}"
  if [ ! -f "$src" ]; then
    echo "skip: $src (not present)"
    continue
  fi
  # Stage next to the destination so the replace is an atomic rename on the same
  # filesystem (a mktemp in /tmp would degrade to copy+unlink across mounts).
  render_snapshot "$src" "$dst" > "$dst.tmp"
  # Preserve the source mode; only replace the file when the content moved.
  if [ -f "$dst" ] && cmp -s "$dst.tmp" "$dst"; then
    rm -f "$dst.tmp"
  else
    chmod --reference="$src" "$dst.tmp" 2>/dev/null || true
    mv -f "$dst.tmp" "$dst"
    changed=1
    echo "updated config/$(basename "$dst")"
  fi
done
[ "$changed" -eq 1 ] || echo "snapshots already current (no diff)"

echo "--- rebuild fontconfig cache (avoids stale/corrupt caches) ---"
if command -v fc-cache >/dev/null 2>&1; then
  fc-cache -f >/dev/null 2>&1 && echo "fc-cache: clean" \
    || echo "note: fc-cache failed"
else
  echo "note: fontconfig not present"
fi

echo "--- git status (nothing staged) ---"
git status --short -- config/

if [ "${1:-}" = "--commit" ]; then
  if [ "$changed" -eq 0 ]; then
    echo "nothing to commit"
  else
    git add config/
    git commit -q -m "Sync live KDE config into snapshots (was $ver)" \
      && echo "committed: $(git rev-parse --short HEAD)"
  fi
fi
echo "=== sync complete ==="
