[ActionPlugins][0]
RightButton;NoModifier=org.kde.contextmenu

[ActionPlugins][1]
RightButton;NoModifier=org.kde.contextmenu

[Containments][1]
ItemGeometries-1920x1080=
ItemGeometriesHorizontal=
activityId=dc45c4fc-ae56-4bdd-b71e-c6008b3097fe
formfactor=0
immutability=1
lastScreen=0
location=0
plugin=org.kde.desktopcontainment
wallpaperplugin=org.kde.image

[Containments][1][Wallpaper][org.kde.image][General]
Image=file:///home/deon/.local/share/wallpapers/kde-setup-02/wavy_lines_v01_5120x2880.png

[Containments][27]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=3
plugin=org.kde.panel
wallpaperplugin=org.kde.image

[Containments][27][Applets][28]
immutability=1
plugin=org.kde.plasma.appmenu

[Containments][27][Applets][29]
immutability=1
plugin=org.kde.plasma.panelspacer

[Containments][27][Applets][30]
immutability=1
plugin=org.kde.plasma.pager

[Containments][27][Applets][31]
immutability=1
plugin=org.kde.plasma.panelspacer

[Containments][27][Applets][32]
activityId=
formfactor=0
immutability=1
lastScreen=-1
location=0
plugin=org.kde.plasma.systemtray
popupHeight=432
popupWidth=432
wallpaperplugin=org.kde.image

[Containments][27][Applets][32][Applets][56]
immutability=1
plugin=org.kde.plasma.clipboard

[Containments][27][Applets][32][Applets][57]
immutability=1
plugin=org.kde.plasma.networkmanagement

[Containments][27][Applets][32][Applets][58]
immutability=1
plugin=org.kde.plasma.volume

[Containments][27][Applets][32][Applets][58][Configuration][General]
migrated=true

[Containments][27][Applets][32][Applets][59]
immutability=1
plugin=org.kde.plasma.notifications

[Containments][27][Applets][32][Applets][60]
immutability=1
plugin=org.kde.plasma.bluetooth

[Containments][27][Applets][32][Applets][61]
immutability=1
plugin=org.kde.plasma.battery

[Containments][27][Applets][32][Applets][62]
immutability=1
plugin=org.kde.plasma.brightness

[Containments][27][Applets][32][General]
extraItems=org.kde.plasma.clipboard,org.kde.plasma.networkmanagement,org.kde.plasma.bluetooth,org.kde.plasma.volume,org.kde.plasma.brightness,org.kde.plasma.battery,org.kde.plasma.notifications
knownItems=org.kde.kdeconnect,org.kde.plasma.vault,org.kde.plasma.networkmanagement,org.kde.plasma.keyboardlayout,org.kde.plasma.printmanager,org.kde.kscreen,org.kde.plasma.bluetooth,org.kde.plasma.volume,org.kde.plasma.cameraindicator,org.kde.plasma.clipboard,org.kde.plasma.devicenotifier,org.kde.plasma.manage-inputmethod,org.kde.plasma.mediacontroller,org.kde.plasma.notifications,org.kde.plasma.battery,org.kde.plasma.brightness,org.kde.plasma.keyboardindicator,org.kde.plasma.weather

[Containments][27][Applets][47]
immutability=1
plugin=org.kde.plasma.digitalclock

[Containments][27][Applets][47][Configuration]
popupHeight=400
popupWidth=560

[Containments][27][General]
AppletOrder=28;29;30;31;32;47

[Containments][48]
activityId=
formfactor=2
immutability=1
lastScreen=0
location=4
plugin=org.kde.panel
wallpaperplugin=org.kde.image

[Containments][48][Applets][49]
immutability=1
plugin=org.kde.plasma.kickoff

[Containments][48][Applets][49][Configuration]
popupHeight=400
popupWidth=560

[Containments][48][Applets][49][Configuration][General]
favoritesPortedToKAstats=true
icon=start-here

[Containments][48][Applets][50]
immutability=1
plugin=org.kde.plasma.icontasks

[Containments][48][Applets][50][Configuration][General]
launchers=applications:org.kde.dolphin.desktop,applications:org.kde.konsole.desktop,applications:org.mozilla.firefox.desktop,applications:com.google.Chrome.desktop,applications:code.desktop
separateLaunchers=true

[Containments][48][Applets][51]
immutability=1
plugin=org.kde.plasma.marginsseparator

[Containments][48][Applets][52]
immutability=1
plugin=org.kde.plasma.trash

[Containments][48][General]
AppletOrder=49;50;51;52

[ScreenMapping]
itemsOnDisabledScreens=
screenMapping=
