[Desktops]
Id_1=db513f95-4887-4927-9a1b-b5ddabdedf00
Id_2=176dd036-2f0e-4816-8a30-72ef90b0c7cf
Id_3=9760b031-0140-4a84-8c18-4fa1ded934fb
Id_4=6888f85f-7c3e-495f-a597-d4e13c7672c7
Number=4
Rows=1

[General]
BorderlessMaximizedWindows=true
decorationTheme=Orchis

[Plugins]
blurEnabled=true
fadeEnabled=true
glideEnabled=true
kwin4_effect_ballEnabled=false
kwin4_effect_kcubeEnabled=false
kwin4_effect_magiclampEnabled=false
maximizeEnabled=true
minimizeEnabled=true
overviewEnabled=true
resizeEnabled=true
scaleEnabled=true
slidingpopupsEnabled=true
wobblywindowsEnabled=false

[Tiling][db513f95-4887-4927-9a1b-b5ddabdedf00][d2dd3887-6a30-48bb-ab55-654327e3f63d]
padding=4
tiles={"layoutDirection":"horizontal","tiles":[{"width":0.25},{"width":0.5},{"width":0.25}]}

[Xwayland]
Scale=1
