[PlasmaViews][Panel 1060]
floating=0
panelVisibility=2
shell=org.kde.plasma.desktop

[PlasmaViews][Panel 1060][Defaults]
offset=0
thickness=32

[PlasmaViews][Panel 1081]
alignment=132
floating=1
panelVisibility=2
shell=org.kde.plasma.desktop

[PlasmaViews][Panel 1081][Defaults]
maxLength=-1
minLength=-1
offset=0
thickness=52
