[Desktops]
Id_1=<desktop-uuid>
Id_2=<desktop-uuid>
Id_3=<desktop-uuid>
Id_4=<desktop-uuid>
Number=4
Rows=1

[General]
BorderlessMaximizedWindows=true
decorationTheme=Orchis

[Plugins]
blurEnabled=true
fadeEnabled=true
glideEnabled=true
kwin4_effect_ballEnabled=false
kwin4_effect_kcubeEnabled=false
kwin4_effect_magiclampEnabled=false
maximizeEnabled=true
minimizeEnabled=true
overviewEnabled=true
resizeEnabled=true
scaleEnabled=true
slidingpopupsEnabled=true
wobblywindowsEnabled=false

[Xwayland]
Scale=1
